export default [
    {
        id: 4,
        tableId: 11487,
        productName: "dasdsd",
        productName1C: "Acrobat Standard 2017 Windows Russian AOO License TLP (1 - 7,999)",
        vendorCode: "61108",
        quantity: 10,
        productId: 8116,
        rests: null,
        ownPrice: 0,
        costPrice: 0,
        retailPrice: 0,
        addExpenses: 0,
        managerComment: "",
        commentForCP: "",
        deliveryDate: 1582743600,
        quantityForSale: 100,
        margin: 20,
        sellingPrice: 10000,
    },
    {
        id: 3,
        tableId: 11487,
        productName: "dasdsd",
        productName1C: "Acrobat Standard 2017 Windows Russian AOO License TLP (1 - 7,999)",
        vendorCode: "61108",
        quantity: 10,
        productId: 8116,
        rests: null,
        ownPrice: 0,
        costPrice: 0,
        retailPrice: 0,
        addExpenses: 0,
        managerComment: "",
        commentForCP: "",
        deliveryDate: 1582743600,
        quantityForSale: 100,
        margin: 20,
        sellingPrice: 10000,
    },
    {
        id: 4,
        tableId: 11487,
        productName: "dasdsd",
        productName1C: "Acrobat Standard 2017 Windows Russian AOO License TLP (1 - 7,999)",
        vendorCode: "61108",
        quantity: 10,
        productId: 8116,
        rests: null,
        ownPrice: 0,
        costPrice: 0,
        retailPrice: 0,
        addExpenses: 0,
        managerComment: "",
        commentForCP: "",
        deliveryDate: 1582743600,
        quantityForSale: 100,
        margin: 20,
        sellingPrice: 10000,
    },
    {
        id: 3,
        tableId: 11487,
        productName: "dasdsd",
        productName1C: "Acrobat Standard 2017 Windows Russian AOO License TLP (1 - 7,999)",
        vendorCode: "61108",
        quantity: 10,
        productId: 8116,
        rests: null,
        ownPrice: 0,
        costPrice: 0,
        retailPrice: 0,
        addExpenses: 0,
        managerComment: "",
        commentForCP: "",
        deliveryDate: 1582743600,
        quantityForSale: 100,
        margin: 20,
        sellingPrice: 10000,
    },
    {
        id: 4,
        tableId: 11487,
        productName: "dasdsd",
        productName1C: "Acrobat Standard 2017 Windows Russian AOO License TLP (1 - 7,999)",
        vendorCode: "61108",
        quantity: 10,
        productId: 8116,
        rests: null,
        ownPrice: 0,
        costPrice: 0,
        retailPrice: 0,
        addExpenses: 0,
        managerComment: "",
        commentForCP: "",
        deliveryDate: 1582743600,
        quantityForSale: 100,
        margin: 20,
        sellingPrice: 10000,
    },
    {
        id: 3,
        tableId: 11487,
        productName: "dasdsd",
        productName1C: "Acrobat Standard 2017 Windows Russian AOO License TLP (1 - 7,999)",
        vendorCode: "61108",
        quantity: 10,
        productId: 8116,
        rests: null,
        ownPrice: 0,
        costPrice: 0,
        retailPrice: 0,
        addExpenses: 0,
        managerComment: "",
        commentForCP: "",
        deliveryDate: 1582743600,
        quantityForSale: 100,
        margin: 20,
        sellingPrice: 10000,
    }
]